package userInfoServices.employeeData.repositories

import userInfoServices.employeeData.entities.EmployeeDetailsEntities
import org.springframework.data.repository.CrudRepository
import org.springframework.stereotype.Repository

@Repository
interface EmployeeDetailsRepository : CrudRepository<EmployeeDetailsEntities,Int>